source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Require only the frameworks we currently use instead of loading everything.
%w(activerecord actionpack actionview railties activejob activemodel).each { |rails_gem|
  gem rails_gem, "~> 7.1.0"
}

gem "pg", "~> 1.5"
gem "puma", "~> 6.0"

# Need to reference all locally, otherwise it'd use the the gemspecs to try to find each gem,
# but we want to test against the local dev versions of them, not the released gems.
gem "judoscale-ruby", path: "../../judoscale-ruby"
gem "judoscale-rails", path: "../../judoscale-rails"
gem "judoscale-solid_queue", path: "../../judoscale-solid_queue"

gem "solid_queue", "~> 1.0"
gem "mission_control-jobs"
gem "sprockets-rails"
