source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Require only the frameworks we currently use instead of loading everything.
%w(activerecord actionpack actionview railties activejob activemodel).each { |rails_gem|
  gem rails_gem, "~> 7.1.0"
}

gem "pg", "~> 1.1"
gem "puma", "~> 6.0"

# Need to reference all locally, otherwise it'd use the the gemspecs to try to find each gem,
# but we want to test against the local dev versions of them, not the released gems.
gem "judoscale-ruby", path: "../../judoscale-ruby"
gem "judoscale-rails", path: "../../judoscale-rails"
gem "judoscale-good_job", path: "../../judoscale-good_job"

gem "good_job", "~> 4.0"
