release: bundle exec rails db:migrate
proxy: npx judoscale-adapter-proxy-server
rails: bundle exec rails server
jobs: DYNO=worker.1 RENDER_SERVICE_ID=srv-abcdefg RENDER_INSTANCE_ID=srv-abcdefg-1234-1234 RENDER_SERVICE_TYPE=worker bundle exec good_job start --max-threads=1
