source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Require only the frameworks we currently use instead of loading everything.
%w(actionpack actionview railties).each { |rails_gem|
  gem rails_gem, "~> 7.0.1"
}

gem "puma", "~> 5.0"

# Need to reference both, otherwise it'd use the `rails-autoscale-web` gemspec to try to find `rails-autoscale-core`,
# but we want to test against the local dev version of it, not a released gem, so we need to specify it too.
gem "rails-autoscale-core", path: "../../rails-autoscale-core"
gem "rails-autoscale-web", path: "../../rails-autoscale-web"
