source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Require only the frameworks we currently use instead of loading everything.
%w(actionpack actionview railties).each { |rails_gem|
  gem rails_gem, "~> 7.1.0"
}

gem "puma", "~> 6.0"

# Need to reference both, otherwise it'd use the `judoscale-rails` gemspec to try to find `judoscale-ruby`,
# but we want to test against the local dev version of it, not a released gem, so we need to specify it too.
gem "judoscale-ruby", path: "../../judoscale-ruby"
gem "judoscale-rails", path: "../../judoscale-rails"
