source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Require only the frameworks we currently use instead of loading everything.
%w(actionpack actionview activejob railties).each { |rails_gem|
  gem rails_gem, "~> 7.1.0"
}

gem "puma", "~> 6.0"

gem "shoryuken", "~> 6.2"
gem "aws-sdk-sqs" # shoryuken integration with AWS SDK v3+
gem "dotenv-rails" # load .env file with AWS credentials

# Need to reference all locally, otherwise it'd use the the gemspecs to try to find each gem,
# but we want to test against the local dev versions of them, not the released gems.
gem "judoscale-ruby", path: "../../judoscale-ruby"
gem "judoscale-rails", path: "../../judoscale-rails"
gem "judoscale-shoryuken", path: "../../judoscale-shoryuken"
