proxy: npx judoscale-adapter-proxy-server

# NOTE: Enable either the `heroku_` processes or the `render_` processes based
# on which env you want to spoof locally.

heroku_rails: DYNO=web.1 bundle exec rails server
heroku_shoryuken: DYNO=worker.1 bundle exec shoryuken -R -C config/shoryuken.yml

# render_rails: RENDER_SERVICE_ID=srv-xyz RENDER_INSTANCE_ID=srv-xyz-1234 RENDER_SERVICE_TYPE=web bundle exec rails server
# render_shoryuken: RENDER_SERVICE_ID=srv-abc RENDER_INSTANCE_ID=srv-abc-1234 RENDER_SERVICE_TYPE=worker bundle exec shoryuken -R -C config/shoryuken.yml
