source "https://rubygems.org"

gemspec name: "judoscale-rack"

gem "judoscale-ruby", path: "../rails-autoscale-core"
gem "minitest"
gem "rake"
gem "rake-release"
gem "debug"
gem "sinatra"
gem "rack-test"
