source "https://rubygems.org"

gemspec name: "judoscale-good_job"

gem "judoscale-ruby", path: "../judoscale-ruby"
gem "activerecord"
gem "pg"
gem "minitest"
gem "rake"
gem "rake-release"
gem "debug"
