source "https://rubygems.org"

gemspec name: "judoscale-que"

gem "judoscale-ruby", path: "../rails-autoscale-core"
gem "activerecord"
gem "pg"
gem "minitest"
gem "rake"
gem "rake-release"
gem "debug"
