source "https://rubygems.org"

gemspec name: "judoscale-ruby"

gem "rake", ">= 12.3.3"
gem "minitest", "~> 5.27" # v5 supports Ruby 3.1
gem "minitest-stub-const"
gem "webmock"
gem "public_suffix", "~> 5.0" # support for older Ruby versions
