source "https://rubygems.org"

gemspec name: "judoscale-solid_queue"

gem "judoscale-ruby", path: "../judoscale-ruby"
gem "activerecord"
gem "pg"
gem "minitest", "5.26.1" # latest version that supports Ruby 2.7
gem "rake"
