source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Require only the frameworks we currently use instead of loading everything.
%w(activerecord actionpack actionview railties).each { |rails_gem|
  gem rails_gem, "~> 7.0.1"
}

gem "pg", "~> 1.1"
gem "puma", "~> 5.0"

gem "que", "~> 2.0"

# Need to reference all locally, otherwise it'd use the the gemspecs to try to find each gem,
# but we want to test against the local dev versions of them, not the released gems.
gem "rails-autoscale-core", path: "../../rails-autoscale-core"
gem "rails-autoscale-web", path: "../../rails-autoscale-web"
gem "rails-autoscale-que", path: "../../rails-autoscale-que"
