release: bundle exec rails db:migrate
proxy: npx judoscale-adapter-proxy-server

# NOTE: Enable either the `heroku_` processes or the `render_` processes based
# on which env you want to spoof locally.

heroku_rails: DYNO=web.1 bundle exec rails server
heroku_que: DYNO=worker.1 bundle exec que -q default -q low -q high

# render_rails: RENDER_SERVICE_ID=srv-xyz RENDER_INSTANCE_ID=srv-xyz-1234 RENDER_SERVICE_TYPE=web bundle exec rails server
# render_que: RENDER_SERVICE_ID=srv-abc RENDER_INSTANCE_ID=srv-abc-1234 RENDER_SERVICE_TYPE=worker bundle exec que -q default -q low -q high
