source "https://rubygems.org"

gemspec name: "judoscale-sidekiq"

gem "rails-autoscale-core", path: "../rails-autoscale-core"
gem "sidekiq", "~> 7.0"
gem "minitest"
gem "rake"
gem "rake-release"
gem "debug"
