source "https://rubygems.org"

gemspec name: "judoscale-sidekiq"

gem "judoscale-ruby", path: "../judoscale-ruby"
gem "sidekiq", "~> 8.0"
gem "minitest", "5.26.1" # latest version that supports Ruby 2.7
gem "rake"
