# frozen_string_literal: true

require "rake/testtask"

Rake::TestTask.new(:test) do |t|
  t.libs = %w[lib test]
  t.pattern = "test/**/*_test.rb"
end

Rake::TestTask.new(:bench) do |t|
  t.libs = %w[lib test]
  t.pattern = "test/benchmarks/**/*_benchmark.rb"
end

task default: :test
