source "https://rubygems.org"

gemspec name: "judoscale-shoryuken"

gem "judoscale-ruby", path: "../judoscale-ruby"
gem "shoryuken", "~> 6.2"
gem "aws-sdk-sqs" # shoryuken integration with AWS SDK v3+
gem "rexml" # aws-sdk-core requires an XML parser.
gem "minitest", "5.25.4" # latest version that supports Ruby 2.6
gem "rake"
# Lock older versions that support Ruby 2.6
gem "aws-eventstream", "~> 1.3.2"
gem "aws-partitions", "~> 1.1109.0"
gem "aws-sigv4", "~> 1.11.0"
gem "aws-sdk-core", "~> 3.224.1"
