proxy: npx judoscale-adapter-proxy-server
rails: bundle exec rails server
sidekiq: DYNO=worker.1 RENDER_SERVICE_ID=srv-abcdefg RENDER_INSTANCE_ID=srv-abcdefg-1234-1234 RENDER_SERVICE_TYPE=worker bundle exec sidekiq -c 2 -q default -q low -q high
